package apphibernate;
// Generated 28-ene-2020 20:22:33 by Hibernate Tools 4.3.1



/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private String modelo;
     private Integer kilometros;
     private Integer matricula;

    public Coches() {
    }

    public Coches(String marca, String modelo, Integer kilometros, Integer matricula) {
       this.marca = marca;
       this.modelo = modelo;
       this.kilometros = kilometros;
       this.numeroBastidor = matricula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getKilometros() {
        return this.kilometros;
    }
    
    public void setKilometros(Integer kilometros) {
        this.kilometros = kilometros;
    }
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }




}


