package apphibernate;
// Generated 28-ene-2020 20:22:33 by Hibernate Tools 4.3.1



/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private Integer telefono;
     private String seccion;

    public Personal() {
    }

    public Personal(String nombre, String apellidos, Integer telefono, String seccion) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.seccion = seccion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }




}


